version: '3.7'
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=marian>lidia
      - MYSQL_DATABASE=shop_management_db
      - MYSQL_USER=oshuser
      - MYSQL_PASSWORD=oshuser
    ports:
      - 5432:3306

  service:
    image: marian/shop-management
    container_name: service
    depends_on:
      - db
    ports:
      - 8282:8282
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=oshuser
      - DATABASE_PASSWORD=oshuser
      - DATABASE_NAME=shop_management_db
      - DATABASE_PORT=3306