version: '3.7'
services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - "/src/main/resources/init.sql:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=marian>lidia
      - MYSQL_DATABASE=shop_management_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 5432:3306

  service:
    image: marianburdianov/shop-management:0.0.1-SNAPSHOT
    container_name: service
    depends_on:
      - mysqldb
    ports:
      - 8282:8282
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=shop_management_db
      - DATABASE_PORT=3306
